#define FMOD_REVERB_FLAGS_DECAYTIMESCALE  0x00000001
#define FMOD_REVERB_FLAGS_REFLECTIONSSCALE  0x00000002
#define FMOD_REVERB_FLAGS_REFLECTIONSDELAYSCALE  0x00000004
#define FMOD_REVERB_FLAGS_REVERBSCALE  0x00000008
#define FMOD_REVERB_FLAGS_REVERBDELAYSCALE  0x00000010
#define FMOD_REVERB_FLAGS_DECAYHFLIMIT  0x00000020
#define FMOD_REVERB_FLAGS_ECHOTIMESCALE  0x00000040
#define FMOD_REVERB_FLAGS_MODULATIONTIMESCALE  0x00000080
#define FMOD_REVERB_FLAGS_DEFAULT  (FMOD_REVERB_FLAGS_DECAYTIMESCALE | FMOD_REVERB_FLAGS_REFLECTIONSSCALE | FMOD_REVERB_FLAGS_REFLECTIONSDELAYSCALE | FMOD_REVERB_FLAGS_REVERBSCALE | FMOD_REVERB_FLAGS_REVERBDELAYSCALE | FMOD_REVERB_FLAGS_DECAYHFLIMIT)

#define FMOD_REVERB_CHANNELFLAGS_DIRECTHFAUTO  0x00000001
#define FMOD_REVERB_CHANNELFLAGS_ROOMAUTO  0x00000002
#define FMOD_REVERB_CHANNELFLAGS_ROOMHFAUTO  0x00000004
#define FMOD_REVERB_CHANNELFLAGS_DEFAULT  (FMOD_REVERB_CHANNELFLAGS_DIRECTHFAUTO | FMOD_REVERB_CHANNELFLAGS_ROOMAUTO| FMOD_REVERB_CHANNELFLAGS_ROOMHFAUTO)

/* This section is here so I can work on this project in pre-FMOD BYOND versions
#define SOUND_MUTE	1
#define SOUND_PAUSED	2
#define SOUND_UPDATE	16
sound
	var
		frequency = 0
		pan = 0
		volume = 100
		priority = 0
		status = 0
		x = 0
		y = 0
		z = 0
		falloff = 1
		environment = -1
		echo
*/

#ifndef SOUND_STREAM
#define SOUND_STREAM	4
#endif